vich_uploader:
    db_driver: orm

    mappings:
        oficios:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
